"""Provides a scripting component.
    Inputs:
        x: The x script variable
        y: The y script variable
    Output:
        a: The a output variable"""

__author__ = "andrewastakhov"

import copy, json
import Rhino.Geometry as rgg
from math import pi

import copy

from math import pi
from scipy.spatial import distance as spdist
import uuid
import numpy as np


class EpsTuple(tuple):
    """
    Tuple with epsilon equal metric.
    It can be useful in geometric transformations with floating point e.g. tessellation .
    --------------------------------------------------------------------------------------------------------------------

    >>> TuplePt.eps = 0.001
    >>> TuplePt((1.0,1.0,1.0))==TuplePt((0.9999,0.9999,0.9999))
    True
    >>> TuplePt((1.0,1.0,1.0))==TuplePt((1.0001,0.9999,0.9999))
    True
    >>> TuplePt((1.0,1.0,1.0))==TuplePt((1.1111,0.9999,0.9999))
    False
    """
    _eps = 0.001

    def __new__(cls, *args, **kwargs):
        return super().__new__(cls, *args, **kwargs)

    @property
    def eps(self): return self._eps

    @eps.setter
    def eps(self, v: float): self._eps = v

    def __eq__(self, other):
        return np.allclose(np.abs((np.asarray(self) - np.asarray(other))) <= self.eps, True)

    def __str__(self):
        return f"{super().__str__()} eps={self.eps}"


def get_prof():
    return rgg.GeometryBase.FromJSON(json.dumps({"version": 10000, "archive3dm": 70, "opennurbs": -1879014078,
                                                 "data": "+n8CAIU+AAAAAAAA+/8CABQAAAAAAAAA4NTXTkfp0xG/5QAQgwEi8Kr1Koj8/wIATT4AAAAAAAAQRAAAAAAAAAAAAAAAAAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA8L8AAAAAAAAAAAAAAAAAAAAARQAAAPD///////e/wO78mXmC2r/gaosOfcHXP3vPkW7gpwdAxdqiQ1/wDUDK6oSko+gyQEGlIGN/SDRAQqUgY3/INUAS6GQYn1o3QG2GlrJAzkJAI5fnn8gyQ0BDnbOsw31EQPetBJpL4kRAGLTQpkZtRUCD1XKBVjZGQIDVcoFWtkZA6PYUXGZ/R0A7BhP82bpHQPEWZOlhH0hANCP8Alg1SUDpM03w35lJQJ6hJcipylBAUrJ2tTEvUUBTsna1Mf9SQAbDx6K5Y1NAzUQnMehXVEB61MG/a6hUQL8/ps+eLVVAp7yYY0pWVkDgJqc7+7VWQMejmc+m3ldADQ9+39ljWEC5nhhuXbRYQH0gePyLqFlAMzHJ6RMNWkAyMcnpE61cQOdBGtebEV1A1OzU3MFwYUAudX3TBaNhQC11fdMFo2lAiP0lyknVaUBpyW27PT1tQMJRFrKBb21AwlEWsoHvbUAc2r6oxSFuQBzavqjFQW5Aa1GSIMFtbkDIXnvO1zpvQCHnI8UbbW9ABahTDDOnb0Dc76DTdM9vQL+SyS0HCXBA+THGEjJTcECIzMlIHmtwQMFrxi1JtXBAkoa/8ZXWcEB9KmbVtupwQO8K/njCB3FAG09SdOQgcUC6LI9dlrpxQDfWsdRv0nFARZaWXLnDckBduEBaStByQKo6DX9o7HJAwFy3fPn4ckAN34OhF/1yQDkj2Jw5FnNAOiPYnDkmc0BnZyyYWz9zQPp/AgCBAAAAAAAAAPv/AgAUAAAAAAAAANvU105H6dMRv+UAEIMBIvD0m+kj/P8CAEkAAAAAAAAAEMBDDwAAABfAkgEAAAAANEAAAAAAAAAAALASr5knqBLAlAEAAAAANEAAAAAAAAAAAPD///////e/wO78mXmC2r8DAAAAFAcmnv9/AoAAAAAAAAAAAPp/AgAOAQAAAAAAAPv/AgAUAAAAAAAAABkRr15RC9QRv/4AEIMBIvBKGnkX/P8CANYAAAAAAAAAEQMAAAABAAAAAwAAAAMAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPC/AAAAAAAAAAAAAAAAAAAAAAQAAADA7vyZeYLav8Du/Jl5gtq/4GqLDn3B1z/gaosOfcHXPwMAAACwEq+ZJ6gSwJQBAAAAADRAAAAAAAAAAAAAAAAAAADwP4PqQYxyaQ/ApZl/YUN6MkAAAAAAAAAAAByNMs9rkO0/gFa+mSeoD8C0B8wM+0o0QAAAAAAAAAAAAAAAAAAA8D8Atj0L+v9/AoAAAAAAAAAAAPp/AgCBAAAAAAAAAPv/AgAUAAAAAAAAANvU105H6dMRv+UAEIMBIvD0m+kj/P8CAEkAAAAAAAAAEIBWvpknqA/AtgfMDPtKNEAAAAAAAAAAAKAaPzOJBwHAMO+b2Q4fNkAAAAAAAAAAAOBqiw59wdc/e8+RbuCnB0ADAAAAN4y9Pf9/AoAAAAAAAAAAAPp/AgAOAQAAAAAAAPv/AgAUAAAAAAAAABkRr15RC9QRv/4AEIMBIvBKGnkX/P8CANYAAAAAAAAAEQMAAAABAAAAAwAAAAMAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPC/AAAAAAAAAAAAAAAAAAAAAAQAAAB7z5Fu4KcHQHvPkW7gpwdAxdqiQ1/wDUDF2qJDX/ANQAMAAACgGj8ziQcBwDDvm9kOHzZAAAAAAAAAAAAAAAAAAADwP9oBuGFDevK/KVfsfM0/NUAAAAAAAAAAAHuNMs9rkO0//A49AAAA9L/M3DezHT44QAAAAAAAAAAAAAAAAAAA8D8A/PpYjv9/AoAAAAAAAAAAAPp/AgCBAAAAAAAAAPv/AgAUAAAAAAAAANvU105H6dMRv+UAEIMBIvD0m+kj/P8CAEkAAAAAAAAAEAAPPQAAAPS/zNw3sx0+OEAAAAAAAAAAAEB7eprn7vO/Hjakt1q0Q0AAAAAAAAAAAMXaokNf8A1AyuqEpKPoMkADAAAAk6YneP9/AoAAAAAAAAAAAPp/AgAOAQAAAAAAAPv/AgAUAAAAAAAAABkRr15RC9QRv/4AEIMBIvBKGnkX/P8CANYAAAAAAAAAEQMAAAABAAAAAwAAAAMAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPC/AAAAAAAAAAAAAAAAAAAAAAQAAADK6oSko+gyQMrqhKSj6DJAQaUgY39INEBBpSBjf0g0QAMAAABAe3qa5+7zvx02pLdatENAAAAAAAAAAAAAAAAAAADwP1hzBDvm1Oy/VSEPYvIjPkAAAAAAAAAAAG3gCiriuug/AIZ6AAAA6L9OAgAAAIBDQAAAAAAAAAAAAAAAAAAA8D8AUbT0E/9/AoAAAAAAAAAAAPp/AgCBAAAAAAAAAPv/AgAUAAAAAAAAANvU105H6dMRv+UAEIMBIvD0m+kj/P8CAEkAAAAAAAAAEACEegAAAOi/UAIAAACAQ0AAAAAAAAAAAAB6hf///+c/UAIAAACAQ0AAAAAAAAAAAEGlIGN/SDRAQqUgY3/INUADAAAAfAluf/9/AoAAAAAAAAAAAPp/AgAOAQAAAAAAAPv/AgAUAAAAAAAAABkRr15RC9QRv/4AEIMBIvBKGnkX/P8CANYAAAAAAAAAEQMAAAABAAAAAwAAAAMAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPC/AAAAAAAAAAAAAAAAAAAAAAQAAABCpSBjf8g1QEKlIGN/yDVAEuhkGJ9aN0AS6GQYn1o3QAMAAAAAfIX////nP1ACAAAAgENAAAAAAAAAAAAAAAAAAADwP/1nyP/FSOw/dBLrDMGTO0AAAAAAAAAAAGM6f2aeoOY/AL7C////8z9QAgAAAEBDQAAAAAAAAAAAAAAAAAAA8D8AlZgobP9/AoAAAAAAAAAAAPp/AgCBAAAAAAAAAPv/AgAUAAAAAAAAANvU105H6dMRv+UAEIMBIvD0m+kj/P8CAEkAAAAAAAAAEAC+wv////M/UAIAAABAQ0AAAAAAAAAAAAC/wv////M/4N83sx0+OEAAAAAAAAAAABLoZBifWjdAbYaWskDOQkADAAAASxg20/9/AoAAAAAAAAAAAPp/AgAOAQAAAAAAAPv/AgAUAAAAAAAAABkRr15RC9QRv/4AEIMBIvBKGnkX/P8CANYAAAAAAAAAEQMAAAABAAAAAwAAAAMAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPC/AAAAAAAAAAAAAAAAAAAAAAQAAABthpayQM5CQG2GlrJAzkJAI5fnn8gyQ0Ajl+efyDJDQAMAAAAAv8L////zP9rfN7MdPjhAAAAAAAAAAAAAAAAAAADwPzcBR2FDevI/4FnsfM0/NUAAAAAAAAAAAFWNMs9rkO0/yfIBM4kHAUBB8pvZDh82QAAAAAAAAAAAAAAAAAAA8D8A6oGLwP9/AoAAAAAAAAAAAPp/AgCBAAAAAAAAAPv/AgAUAAAAAAAAANvU105H6dMRv+UAEIMBIvD0m+kj/P8CAEkAAAAAAAAAEADzATOJBwFAQPKb2Q4fNkAAAAAAAAAAAAAvgZknqA9A0ArMDPtKNEAAAAAAAAAAACOX55/IMkNAQ52zrMN9READAAAAIFXni/9/AoAAAAAAAAAAAPp/AgAOAQAAAAAAAPv/AgAUAAAAAAAAABkRr15RC9QRv/4AEIMBIvBKGnkX/P8CANYAAAAAAAAAEQMAAAABAAAAAwAAAAMAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPC/AAAAAAAAAAAAAAAAAAAAAAQAAABDnbOsw31EQEOds6zDfURA960EmkviRED3rQSaS+JEQAMAAAAgL4GZJ6gPQNAKzAz7SjRAAAAAAAAAAAAAAAAAAADwPy9sCYxyaQ9APZ1/YUN6MkAAAAAAAAAAADSOMs9rkO0/EH+QmSeoEkC0BAAAAAA0QAAAAAAAAAAAAAAAAAAA8D8AZ4Q5Of9/AoAAAAAAAAAAAPp/AgCBAAAAAAAAAPv/AgAUAAAAAAAAANvU105H6dMRv+UAEIMBIvD0m+kj/P8CAEkAAAAAAAAAEAB/kJknqBJAsAQAAAAANEAAAAAAAAAAAACw8P///xZAsAQAAAAANEAAAAAAAAAAAPetBJpL4kRAGLTQpkZtRUADAAAAczABQP9/AoAAAAAAAAAAAPp/AgAOAQAAAAAAAPv/AgAUAAAAAAAAABkRr15RC9QRv/4AEIMBIvBKGnkX/P8CANYAAAAAAAAAEQMAAAABAAAAAwAAAAMAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPC/AAAAAAAAAAAAAAAAAAAAAAQAAAAYtNCmRm1FQBi00KZGbUVAg9VygVY2RkCD1XKBVjZGQAMAAAAAsPD///8WQLAEAAAAADRAAAAAAAAAAAAAAAAAAADwPzuTCMB7rRFAERIfAMZILEAAAAAAAAAAAFU8f2aeoOY/+K/w////GECwBAAAAIA0QAAAAAAAAAAAAAAAAAAA8D8APYahIv9/AoAAAAAAAAAAAPp/AgCBAAAAAAAAAPv/AgAUAAAAAAAAANvU105H6dMRv+UAEIMBIvD0m+kj/P8CAEkAAAAAAAAAEACw8P///xhAsAQAAACANEAAAAAAAAAAAACw8P///xhAsAQAAACANUAAAAAAAAAAAIPVcoFWNkZAgNVygVa2RkADAAAAeBtPsP9/AoAAAAAAAAAAAPp/AgAOAQAAAAAAAPv/AgAUAAAAAAAAABkRr15RC9QRv/4AEIMBIvBKGnkX/P8CANYAAAAAAAAAEQMAAAABAAAAAwAAAAMAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPC/AAAAAAAAAAAAAAAAAAAAAAQAAACA1XKBVrZGQIDVcoFWtkZA6PYUXGZ/R0Do9hRcZn9HQAMAAAAAsPD///8YQLAEAAAAgDVAAAAAAAAAAAAAAAAAAADwP9mRCMB7rRFA9PbuzNkcL0AAAAAAAAAAAGM6f2aeoOY/ALDw////FkCwBAAAAAA2QAAAAAAAAAAAAAAAAAAA8D8A9L66mv9/AoAAAAAAAAAAAPp/AgCBAAAAAAAAAPv/AgAUAAAAAAAAANvU105H6dMRv+UAEIMBIvD0m+kj/P8CAEkAAAAAAAAAEACw8P///xZAsAQAAAAANkAAAAAAAAAAAEA1AABjJBVAsAQAAAAANkAAAAAAAAAAAOj2FFxmf0dAOwYT/Nm6R0ADAAAAWal6Mf9/AoAAAAAAAAAAAPp/AgAOAQAAAAAAAPv/AgAUAAAAAAAAABkRr15RC9QRv/4AEIMBIvBKGnkX/P8CANYAAAAAAAAAEQMAAAABAAAAAwAAAAMAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPC/AAAAAAAAAAAAAAAAAAAAAAQAAAA7BhP82bpHQDsGE/zZukdA8RZk6WEfSEDxFmTpYR9IQAMAAABANQAAYyQVQLAEAAAAADZAAAAAAAAAAAAAAAAAAADwP2WK2pp1xBJAUcVyHkpTNEAAAAAAAAAAABKNMs9rkO0/lEGYGVm6E0DBB2aGfSU2QAAAAAAAAAAAAAAAAAAA8D8AO+dcUv9/AoAAAAAAAAAAAPp/AgCBAAAAAAAAAPv/AgAUAAAAAAAAANvU105H6dMRv+UAEIMBIvD0m+kj/P8CAEkAAAAAAAAAEIBBmBlZuhNAwAdmhn0lNkAAAAAAAAAAAIB4ETPsKwtAEOlpRpauN0AAAAAAAAAAAPEWZOlhH0hANCP8Alg1SUADAAAAgI7U2v9/AoAAAAAAAAAAAPp/AgAOAQAAAAAAAPv/AgAUAAAAAAAAABkRr15RC9QRv/4AEIMBIvBKGnkX/P8CANYAAAAAAAAAEQMAAAABAAAAAwAAAAMAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPC/AAAAAAAAAAAAAAAAAAAAAAQAAAA0I/wCWDVJQDQj/AJYNUlA6TNN8N+ZSUDpM03w35lJQAMAAAAAeBEz7CsLQBDpaUaWrjdAAAAAAAAAAAAAAAAAAADwP6rHPJhXBQhAls8hkrwDNkAAAAAAAAAAAN+NMs9rkO0/hl/h////CUAA5gPAGAk4QAAAAAAAAAAAAAAAAAAA8D8AOsxs7/9/AoAAAAAAAAAAAPp/AgCBAAAAAAAAAPv/AgAUAAAAAAAAANvU105H6dMRv+UAEIMBIvD0m+kj/P8CAEkAAAAAAAAAEIBf4f///wlAAOYDwBgJOEAAAAAAAAAAAIBe4f///wlAUAIAAAAAREAAAAAAAAAAAOkzTfDfmUlAnqElyKnKUEADAAAAeAGvMP9/AoAAAAAAAAAAAPp/AgAOAQAAAAAAAPv/AgAUAAAAAAAAABkRr15RC9QRv/4AEIMBIvBKGnkX/P8CANYAAAAAAAAAEQMAAAABAAAAAwAAAAMAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPC/AAAAAAAAAAAAAAAAAAAAAAQAAACeoSXIqcpQQJ6hJcipylBAUrJ2tTEvUUBSsna1MS9RQAMAAACAXuH///8JQFUCAAAAAERAAAAAAAAAAAAAAAAAAADwP0e3MbOAYgJAUvu62dRnPkAAAAAAAAAAAIk7f2aeoOY/IK/w////GEBWAgAAAIBFQAAAAAAAAAAAAAAAAAAA8D8AWpqBPv9/AoAAAAAAAAAAAPp/AgCBAAAAAAAAAPv/AgAUAAAAAAAAANvU105H6dMRv+UAEIMBIvD0m+kj/P8CAEkAAAAAAAAAEECv8P///xhAWAIAAACARUAAAAAAAAAAAKBX+P///ypAYAIAAACARUAAAAAAAAAAAFKydrUxL1FAU7J2tTH/UkADAAAAcKX+UP9/AoAAAAAAAAAAAPp/AgAOAQAAAAAAAPv/AgAUAAAAAAAAABkRr15RC9QRv/4AEIMBIvBKGnkX/P8CANYAAAAAAAAAEQMAAAABAAAAAwAAAAMAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPC/AAAAAAAAAAAAAAAAAAAAAAQAAABTsna1Mf9SQFOydrUx/1JABsPHorljU0AGw8eiuWNTQAMAAACYV/j///8qQGACAAAAgEVAAAAAAAAAAAAAAAAAAADwP2jLrVmjVSdAr/u62dRnPkAAAAAAAAAAAMU7f2aeoOY/zCv8//9/MEBjAgAAAABEQAAAAAAAAAAAAAAAAAAA8D8ADyMznv9/AoAAAAAAAAAAAPp/AgCBAAAAAAAAAPv/AgAUAAAAAAAAANvU105H6dMRv+UAEIMBIvD0m+kj/P8CAEkAAAAAAAAAENAr/P//fzBAYAIAAAAAREAAAAAAAAAAAOAr/P//fzBA0P5A46IXQkAAAAAAAAAAAAbDx6K5Y1NAzUQnMehXVEADAAAA9gwckf9/AoAAAAAAAAAAAPp/AgAOAQAAAAAAAPv/AgAUAAAAAAAAABkRr15RC9QRv/4AEIMBIvBKGnkX/P8CANYAAAAAAAAAEQMAAAABAAAAAwAAAAMAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPC/AAAAAAAAAAAAAAAAAAAAAAQAAADNRCcx6FdUQM1EJzHoV1RAetTBv2uoVEB61MG/a6hUQAMAAADgK/z//38wQNH+QOOiF0JAAAAAAAAAAAAAAAAAAADwPx500dIdrypAH2DfHryrPEAAAAAAAAAAAPjGe+sc4Ok/nuGV2ImdL0BxOuiY2J1BQAAAAAAAAAAAAAAAAAAA8D8A7gMYhv9/AoAAAAAAAAAAAPp/AgBeAQAAAAAAAPv/AgAUAAAAAAAAABkRr15RC9QRv/4AEIMBIvBKGnkX/P8CACYBAAAAAAAAEQMAAAABAAAAAwAAAAUAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPC/AAAAAAAAAAAAAAAAAAAAAAYAAAB61MG/a6hUQHrUwb9rqFRAHAq0RwXrVEAcCrRHBetUQL8/ps+eLVVAvz+mz54tVUAFAAAAqOGV2ImdL0BwOuiY2J1BQAAAAAAAAAAAAAAAAAAA8D8Mmz2+bDomQOhDAp+wuj1AAAAAAAAAAAB0ML8y6cPrPxp1mSVKQihAVAAXsbQvP0AAAAAAAAAAAAAAAAAAAPA/4GQo23neI0Bv5KM/rGM4QAAAAAAAAAAAdDC/MunD6z8G8bX2fIUrQC98d3d39zlAAAAAAAAAAAAAAAAAAADwPwBBWuNw/38CgAAAAAAAAAAA+n8CAIEAAAAAAAAA+/8CABQAAAAAAAAA29TXTkfp0xG/5QAQgwEi8PSb6SP8/wIASQAAAAAAAAAQAPG19nyFK0AwfHd3d/c5QAAAAAAAAAAA0FUzC/ooMUAQ4QrFrdA2QAAAAAAAAAAAvz+mz54tVUCnvJhjSlZWQAMAAACX1jHX/38CgAAAAAAAAAAA+n8CAA4BAAAAAAAA+/8CABQAAAAAAAAAGRGvXlEL1BG//gAQgwEi8EoaeRf8/wIA1gAAAAAAAAARAwAAAAEAAAADAAAAAwAAAAAAAAAAAAAAAAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA8L8AAAAAAAAAAAAAAAAAAAAABAAAAKe8mGNKVlZAp7yYY0pWVkDgJqc7+7VWQOAmpzv7tVZAAwAAANBVMwv6KDFAEOEKxa3QNkAAAAAAAAAAAAAAAAAAAPA/SA2lqqqqKUB/AwAAAIAwQAAAAAAAAAAAe3d3d3d35z8VAsX0BdcxQBThCsWt0DZAAAAAAAAAAAAAAAAAAADwPwD4O8sZ/38CgAAAAAAAAAAA+n8CAIEAAAAAAAAA+/8CABQAAAAAAAAA29TXTkfp0xG/5QAQgwEi8PSb6SP8/wIASQAAAAAAAAAQIALF9AXXMUAQ4QrFrdA2QAAAAAAAAAAAYF+dhEE9NUBAfHd3d/c5QAAAAAAAAAAA4CanO/u1VkDHo5nPpt5XQAMAAACn37kM/38CgAAAAAAAAAAA+n8CAF4BAAAAAAAA+/8CABQAAAAAAAAAGRGvXlEL1BG//gAQgwEi8EoaeRf8/wIAJgEAAAAAAAARAwAAAAEAAAADAAAABQAAAAAAAAAAAAAAAAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA8L8AAAAAAAAAAAAAAAAAAAAABgAAAMejmc+m3ldAx6OZz6beV0Bq2YtXQCFYQGrZi1dAIVhADQ9+39ljWEAND37f2WNYQAUAAABwX52EQT01QEB8d3d39zlAAAAAAAAAAAAAAAAAAADwP9tF5iEKbzRAgeSjP6xjOEAAAAAAAAAAAG8wvzLpw+s/VJ0r7dreNkBqABextC8/QAAAAAAAAAAAAAAAAAAA8D+xqluwEEEzQPdDAp+wuj1AAAAAAAAAAABvML8y6cPrP/5mrRM7MTNAdTromNidQUAAAAAAAAAAAAAAAAAAAPA/AKqu8Y7/fwKAAAAAAAAAAAD6fwIADgEAAAAAAAD7/wIAFAAAAAAAAAAZEa9eUQvUEb/+ABCDASLwShp5F/z/AgDWAAAAAAAAABEDAAAAAQAAAAMAAAADAAAAAAAAAAAAAAAAAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAAAADwvwAAAAAAAAAAAAAAAAAAAAAEAAAADQ9+39ljWEAND37f2WNYQLmeGG5dtFhAuZ4Ybl20WEADAAAA+GatEzsxM0B4OuiY2J1BQAAAAAAAAAAAAAAAAAAA8D9P60BwIestQJle3x68qzxAAAAAAAAAAACYxXvrHODpP94r/P//fzJA1/5A46IXQkAAAAAAAAAAAAAAAAAAAPA/AMvMZ1f/fwKAAAAAAAAAAAD6fwIAgQAAAAAAAAD7/wIAFAAAAAAAAADb1NdOR+nTEb/lABCDASLw9JvpI/z/AgBJAAAAAAAAABDgK/z//38yQND+QOOiF0JAAAAAAAAAAADQK/z//38yQGACAAAAAERAAAAAAAAAAAC5nhhuXbRYQH0gePyLqFlAAwAAANaHGpj/fwKAAAAAAAAAAAD6fwIADgEAAAAAAAD7/wIAFAAAAAAAAAAZEa9eUQvUEb/+ABCDASLwShp5F/z/AgDWAAAAAAAAABEDAAAAAQAAAAMAAAADAAAAAAAAAAAAAAAAAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAAAADwvwAAAAAAAAAAAAAAAAAAAAAEAAAAfSB4/IuoWUB9IHj8i6hZQDMxyekTDVpAMzHJ6RMNWkADAAAA0Cv8//9/MkBlAgAAAABEQAAAAAAAAAAAAAAAAAAA8D/Rsn0mtykqQKD7utnUZz5AAAAAAAAAAAC2O39mnqDmP8wr/P//fzVAZgIAAACARUAAAAAAAAAAAAAAAAAAAPA/AEoRaML/fwKAAAAAAAAAAAD6fwIAgQAAAAAAAAD7/wIAFAAAAAAAAADb1NdOR+nTEb/lABCDASLw9JvpI/z/AgBJAAAAAAAAABDQK/z//381QGgCAAAAgEVAAAAAAAAAAADQK/z///8/QHACAAAAgEVAAAAAAAAAAAAzMcnpEw1aQDIxyekTrVxAAwAAAD/q1DT/fwKAAAAAAAAAAAD6fwIADgEAAAAAAAD7/wIAFAAAAAAAAAAZEa9eUQvUEb/+ABCDASLwShp5F/z/AgDWAAAAAAAAABEDAAAAAQAAAAMAAAADAAAAAAAAAAAAAAAAAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAAAADwvwAAAAAAAAAAAAAAAAAAAAAEAAAAMjHJ6ROtXEAyMcnpE61cQOdBGtebEV1A50Ea15sRXUADAAAA0Cv8////P0BwAgAAAIBFQAAAAAAAAAAAAAAAAAAA8D+IgRbgIPs2QOj4utnUZz5AAAAAAAAAAACuOX9mnqDmP+wV/v//P0BAcAIAAADARUAAAAAAAAAAAAAAAAAAAPA/AHMCuT//fwKAAAAAAAAAAAD6fwIA6QAAAAAAAAD7/wIAFAAAAAAAAADm1NdOR+nTEb/lABCDASLwTpy72/z/AgCxAAAAAAAAABAFAAAA6BX+//8/QEBwAgAAAMBFQAAAAAAAAAAA4BX+//8/QEAInJmZmVlLQAAAAAAAAAAAeK+XmZkZQEBwAgAAAIBLQAAAAAAAAAAA2BX+//8/QEDYaGZmZqZLQAAAAAAAAAAA0BX+//8/QEA4AQAAAKBQQAAAAAAAAAAABQAAAOdBGtebEV1Asw7no2jeX0DIDWLIj/lfQG6GbnZbCmBA1OzU3MFwYUADAAAAJfmQHv9/AoAAAAAAAAAAAPp/AgAOAQAAAAAAAPv/AgAUAAAAAAAAABkRr15RC9QRv/4AEIMBIvBKGnkX/P8CANYAAAAAAAAAEQMAAAABAAAAAwAAAAMAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPC/AAAAAAAAAAAAAAAAAAAAAAQAAADU7NTcwXBhQNTs1NzBcGFALnV90wWjYUAudX3TBaNhQAMAAADQFf7//z9AQDgBAAAAoFBAAAAAAAAAAAAAAAAAAADwP8yCFuAg+zZAmDNN0yWwR0AAAAAAAAAAABg7f2aeoOY/oCv8////P0A4AQAAAMBQQAAAAAAAAAAAAAAAAAAA8D8APiQg7/9/AoAAAAAAAAAAAPp/AgCBAAAAAAAAAPv/AgAUAAAAAAAAANvU105H6dMRv+UAEIMBIvD0m+kj/P8CAEkAAAAAAAAAEKAr/P///z9AOAEAAADAUEAAAAAAAAAAADDqAQAAAEDAGAEAAADAUEAAAAAAAAAAAC51fdMFo2FALXV90wWjaUADAAAAgYf7xv9/AoAAAAAAAAAAAPp/AgAOAQAAAAAAAPv/AgAUAAAAAAAAABkRr15RC9QRv/4AEIMBIvBKGnkX/P8CANYAAAAAAAAAEQMAAAABAAAAAwAAAAMAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPC/AAAAAAAAAAAAAAAAAAAAAAQAAAAtdX3TBaNpQC11fdMFo2lAiP0lyknVaUCI/SXKSdVpQAMAAAAw6gEAAABAwBgBAAAAwFBAAAAAAAAAAAAAAAAAAADwP07rG+Ag+zbAYzFN0yWwR0AAAAAAAAAAACY5f2aeoOY/L+oBAABAQMAYAQAAAKBQQAAAAAAAAAAAAAAAAAAA8D8AMLqLjP9/AoAAAAAAAAAAAPp/AgDpAAAAAAAAAPv/AgAUAAAAAAAAAObU105H6dMRv+UAEIMBIvBOnLvb/P8CALEAAAAAAAAAEAUAAAAw6gEAAEBAwBgBAAAAoFBAAAAAAAAAAAAo6gEAAEBAwJhoZmZmpktAAAAAAAAAAADAg5uZmRlAwDACAAAAgEtAAAAAAAAAAAAg6gEAAEBAwMibmZmZWUtAAAAAAAAAAAAY6gEAAEBAwDACAAAAwENAAAAAAAAAAAAFAAAAiP0lyknVaUDvY4wwsDtrQHnjycJDSWtAAmMHVddWa0BpyW27PT1tQAMAAAD44eDX/38CgAAAAAAAAAAA+n8CAA4BAAAAAAAA+/8CABQAAAAAAAAAGRGvXlEL1BG//gAQgwEi8EoaeRf8/wIA1gAAAAAAAAARAwAAAAEAAAADAAAAAwAAAAAAAAAAAAAAAAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA8L8AAAAAAAAAAAAAAAAAAAAABAAAAGnJbbs9PW1Aacltuz09bUDCURaygW9tQMJRFrKBb21AAwAAABjqAQAAQEDAMAIAAADAQ0AAAAAAAAAAAAAAAAAAAPA/1u0b4CD7NsD5E+sMwZM7QAAAAAAAAAAAzTt/Zp6g5j8Y6gEAAABAwDACAAAAgENAAAAAAAAAAAAAAAAAAADwPwD8lCMq/38CgAAAAAAAAAAA+n8CAIEAAAAAAAAA+/8CABQAAAAAAAAA29TXTkfp0xG/5QAQgwEi8PSb6SP8/wIASQAAAAAAAAAQGOoBAAAAQMAwAgAAAIBDQAAAAAAAAAAAMNQDAAAAPMA4AgAAAIBDQAAAAAAAAAAAwlEWsoFvbUDCURayge9tQAMAAAAnkbLK/38CgAAAAAAAAAAA+n8CAA4BAAAAAAAA+/8CABQAAAAAAAAAGRGvXlEL1BG//gAQgwEi8EoaeRf8/wIA1gAAAAAAAAARAwAAAAEAAAADAAAAAwAAAAAAAAAAAAAAAAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA8L8AAAAAAAAAAAAAAAAAAAAABAAAAMJRFrKB721AwlEWsoHvbUAc2r6oxSFuQBzavqjFIW5AAwAAAC7UAwAAADzAOAIAAACAQ0AAAAAAAAAAAAAAAAAAAPA/ZwsYIAhyM8CAEusMwZM7QAAAAAAAAAAAkDp/Zp6g5j8w1AMAAIA7wDgCAAAAwENAAAAAAAAAAAAAAAAAAADwPwA9gPoW/38CgAAAAAAAAAAA+n8CAIEAAAAAAAAA+/8CABQAAAAAAAAA29TXTkfp0xG/5QAQgwEi8PSb6SP8/wIASQAAAAAAAAAQMNQDAACAO8A4AgAAAMBDQAAAAAAAAAAAMNQDAACAO8A4AgAAAEBEQAAAAAAAAAAAHNq+qMUhbkAc2r6oxUFuQAMAAADK9WLE/38CgAAAAAAAAAAA+n8CAA4BAAAAAAAA+/8CABQAAAAAAAAAGRGvXlEL1BG//gAQgwEi8EoaeRf8/wIA1gAAAAAAAAARAwAAAAEAAAADAAAAAwAAAAAAAAAAAAAAAAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA8L8AAAAAAAAAAAAAAAAAAAAABAAAABzavqjFQW5AHNq+qMVBbkBrUZIgwW1uQGtRkiDBbW5AAwAAADDUAwAAgDvAOAIAAABAREAAAAAAAAAAAAAAAAAAAPA/My/2GslANcAauw4izJ4/QAAAAAAAAAAAu+UKKuK66D/NO0xvteg7wBTs0Tx3f0RAAAAAAAAAAAAAAAAAAADwPwDGKNJN/38CgAAAAAAAAAAA+n8CAIEAAAAAAAAA+/8CABQAAAAAAAAA29TXTkfp0xG/5QAQgwEi8PSb6SP8/wIASQAAAAAAAAAQ0DtMb7XoO8AS7NE8d39EQAAAAAAAAAAA8NADAACANcDIAAAAAIBEQAAAAAAAAAAAa1GSIMFtbkDIXnvO1zpvQAMAAAC0KXUp/38CgAAAAAAAAAAA+n8CAA4BAAAAAAAA+/8CABQAAAAAAAAAGRGvXlEL1BG//gAQgwEi8EoaeRf8/wIA1gAAAAAAAAARAwAAAAEAAAADAAAAAwAAAAAAAAAAAAAAAAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA8L8AAAAAAAAAAAAAAAAAAAAABAAAAMhee87XOm9AyF57ztc6b0Ah5yPFG21vQCHnI8UbbW9AAwAAAPDQAwAAgDXAyAAAAACAREAAAAAAAAAAAAAAAAAAAPA/doKIJrcpKsB8BVPzyv08QAAAAAAAAAAAmDt/Zp6g5j/u0AMAAIAywMgAAAAAAENAAAAAAAAAAAAAAAAAAADwPwB5i1Ya/38CgAAAAAAAAAAA+n8CAIEAAAAAAAAA+/8CABQAAAAAAAAA29TXTkfp0xG/5QAQgwEi8PSb6SP8/wIASQAAAAAAAAAQ8NADAACAMsDIAAAAAABDQAAAAAAAAAAA8NADAACAMsA5/UDjohdCQAAAAAAAAAAAIecjxRttb0AFqFMMM6dvQAMAAAC5hSgb/38CgAAAAAAAAAAA+n8CAA4BAAAAAAAA+/8CABQAAAAAAAAAGRGvXlEL1BG//gAQgwEi8EoaeRf8/wIA1gAAAAAAAAARAwAAAAEAAAADAAAAAwAAAAAAAAAAAAAAAAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA8L8AAAAAAAAAAAAAAAAAAAAABAAAAAWoUwwzp29ABahTDDOnb0Dc76DTdM9vQNzvoNN0z29AAwAAAPDQAwAAgDLAOf1A46IXQkAAAAAAAAAAAAAAAAAAAPA/iklNcCHrLcAjXd8evKs8QAAAAAAAAAAAncZ76xzg6T8EDLUTOzEzwNk46JjYnUFAAAAAAAAAAAAAAAAAAADwPwCNrH3e/38CgAAAAAAAAAAA+n8CAF4BAAAAAAAA+/8CABQAAAAAAAAAGRGvXlEL1BG//gAQgwEi8EoaeRf8/wIAJgEAAAAAAAARAwAAAAEAAAADAAAABQAAAAAAAAAAAAAAAAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA8L8AAAAAAAAAAAAAAAAAAAAABgAAANzvoNN0z29A3O+g03TPb0CtCpqXwfBvQK0KmpfB8G9Av5LJLQcJcEC/ksktBwlwQAUAAAAEDLUTOzEzwNk46JjYnUFAAAAAAAAAAAAAAAAAAADwP71MYrAQQTPALUECn7C6PUAAAAAAAAAAAHgwvzLpw+s/TEIz7dreNsAu/RaxtC8/QAAAAAAAAAAAAAAAAAAA8D/b5+whCm80wLrhoz+sYzhAAAAAAAAAAAB4ML8y6cPrP2IEpYRBPTXACnl3d3f3OUAAAAAAAAAAAAAAAAAAAPA/AItuFHj/fwKAAAAAAAAAAAD6fwIAgQAAAAAAAAD7/wIAFAAAAAAAAADb1NdOR+nTEb/lABCDASLw9JvpI/z/AgBJAAAAAAAAABBkBKWEQT01wAh5d3d39zlAAAAAAAAAAAAQp8z0BdcxwODdCsWt0DZAAAAAAAAAAAC/ksktBwlwQPkxxhIyU3BAAwAAALs8uzb/fwKAAAAAAAAAAAD6fwIADgEAAAAAAAD7/wIAFAAAAAAAAAAZEa9eUQvUEb/+ABCDASLwShp5F/z/AgDWAAAAAAAAABEDAAAAAQAAAAMAAAADAAAAAAAAAAAAAAAAAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAAAADwvwAAAAAAAAAAAAAAAAAAAAAEAAAA+THGEjJTcED5McYSMlNwQIjMyUgea3BAiMzJSB5rcEADAAAAEKfM9AXXMcDi3QrFrdA2QAAAAAAAAAAAAAAAAAAA8D+MRLCqqqopwNgBAAAAgDBAAAAAAAAAAABqeHd3d3fnP9D6Ogv6KDHA4t0Kxa3QNkAAAAAAAAAAAAAAAAAAAPA/AKt11aP/fwKAAAAAAAAAAAD6fwIAgQAAAAAAAAD7/wIAFAAAAAAAAADb1NdOR+nTEb/lABCDASLw9JvpI/z/AgBJAAAAAAAAABDO+joL+igxwODdCsWt0DZAAAAAAAAAAADwOsX2fIUrwAh5d3d39zlAAAAAAAAAAACIzMlIHmtwQMFrxi1JtXBAAwAAAAKpCz7/fwKAAAAAAAAAAAD6fwIAXgEAAAAAAAD7/wIAFAAAAAAAAAAZEa9eUQvUEb/+ABCDASLwShp5F/z/AgAmAQAAAAAAABEDAAAAAQAAAAMAAAAFAAAAAAAAAAAAAAAAAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAAAADwvwAAAAAAAAAAAAAAAAAAAAAGAAAAwWvGLUm1cEDBa8YtSbVwQCr5wo/vxXBAKvnCj+/FcECShr/xldZwQJKGv/GV1nBABQAAAPA6xfZ8hSvACHl3d3f3OUAAAAAAAAAAAAAAAAAAAPA/3Kg123neI8C34aM/rGM4QAAAAAAAAAAAdDC/MunD6z8Wv6glSkIowDH9FrG0Lz9AAAAAAAAAAAAAAAAAAADwPxzfSr5sOibAMUECn7C6PUAAAAAAAAAAAHQwvzLpw+s/tCul2ImdL8DcOOiY2J1BQAAAAAAAAAAAAAAAAAAA8D8Aw4ozUv9/AoAAAAAAAAAAAPp/AgAOAQAAAAAAAPv/AgAUAAAAAAAAABkRr15RC9QRv/4AEIMBIvBKGnkX/P8CANYAAAAAAAAAEQMAAAABAAAAAwAAAAMAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPC/AAAAAAAAAAAAAAAAAAAAAAQAAACShr/xldZwQJKGv/GV1nBAfSpm1bbqcEB9KmbVtupwQAMAAAC4K6XYiZ0vwNo46JjYnUFAAAAAAAAAAAAAAAAAAADwP9HQ3dIdryrAM13fHryrPEAAAAAAAAAAAKrGe+sc4Ok/8dADAACAMMA6/UDjohdCQAAAAAAAAAAAAAAAAAAA8D8AOkDzUv9/AoAAAAAAAAAAAPp/AgCBAAAAAAAAAPv/AgAUAAAAAAAAANvU105H6dMRv+UAEIMBIvD0m+kj/P8CAEkAAAAAAAAAEPDQAwAAgDDAOv1A46IXQkAAAAAAAAAAAPDQAwAAgDDAyAAAAAAAQ0AAAAAAAAAAAH0qZtW26nBA7wr+eMIHcUADAAAA+WT7Ov9/AoAAAAAAAAAAAPp/AgAOAQAAAAAAAPv/AgAUAAAAAAAAABkRr15RC9QRv/4AEIMBIvBKGnkX/P8CANYAAAAAAAAAEQMAAAABAAAAAwAAAAMAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPC/AAAAAAAAAAAAAAAAAAAAAAQAAADvCv54wgdxQO8K/njCB3FAG09SdOQgcUAbT1J05CBxQAMAAADw0AMAAIAwwMgAAAAAAENAAAAAAAAAAAAAAAAAAADwP0+buFmjVSfAxAVT88r9PEAAAAAAAAAAANQ7f2aeoOY/4KEHAAAAK8DLAAAAAIBEQAAAAAAAAAAAAAAAAAAA8D8Am0weKf9/AoAAAAAAAAAAAPp/AgAJAQAAAAAAAPv/AgAUAAAAAAAAAObU105H6dMRv+UAEIMBIvBOnLvb/P8CANEAAAAAAAAAEAYAAADgoQcAAAArwMgAAAAAgERAAAAAAAAAAACoDCaBXUMpwMgAAAAAgERAAAAAAAAAAACoMqPyyXogwFTgLxfRUkRAAAAAAAAAAABQuxPAwKofwMa4j0sEdkRAAAAAAAAAAADA9xQdJ5EewIZj6eapTERAAAAAAAAAAABgbmN89a0QwLHldsLxKERAAAAAAAAAAAAGAAAAG09SdOQgcUDGW0mIyS5xQL75IihIdXFAhLlB8RF8cUBIeWC624JxQLosj12WunFAAwAAAGvUbBf/fwKAAAAAAAAAAAD6fwIADgEAAAAAAAD7/wIAFAAAAAAAAAAZEa9eUQvUEb/+ABCDASLwShp5F/z/AgDWAAAAAAAAABEDAAAAAQAAAAMAAAADAAAAAAAAAAAAAAAAAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAAAADwvwAAAAAAAAAAAAAAAAAAAAAEAAAAuiyPXZa6cUC6LI9dlrpxQDfWsdRv0nFAN9ax1G/ScUADAAAAYG5jfPWtEMCw5XbC8ShEQAAAAAAAAAAAAAAAAAAA8D/kvfipaBsDwMSxoXWDkz1AAAAAAAAAAAA+OSoMMoTnP3+HHgAAAArA3O7BGFupQ0AAAAAAAAAAAAAAAAAAAPA/AH/YjP//fwKAAAAAAAAAAAD6fwIAgQAAAAAAAAD7/wIAFAAAAAAAAADb1NdOR+nTEb/lABCDASLw9JvpI/z/AgBJAAAAAAAAABCAhx4AAAAKwNzuwRhbqUNAAAAAAAAAAACAhx4AAAAKwMjcN7MdPjhAAAAAAAAAAAA31rHUb9JxQEWWlly5w3JAAwAAAGUeoLb/fwKAAAAAAAAAAAD6fwIADgEAAAAAAAD7/wIAFAAAAAAAAAAZEa9eUQvUEb/+ABCDASLwShp5F/z/AgDWAAAAAAAAABEDAAAAAQAAAAMAAAADAAAAAAAAAAAAAAAAAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAAAADwvwAAAAAAAAAAAAAAAAAAAAAEAAAARZaWXLnDckBFlpZcucNyQF24QFpK0HJAXbhAWkrQckADAAAAgIceAAAACsDI3DezHT44QAAAAAAAAAAAAAAAAAAA8D+kR3WYVwUIwHTMIZK8AzZAAAAAAAAAAACAjTLPa5DtP6G4fmbYVwzA6uIDwBiJN0AAAAAAAAAAAAAAAAAAAPA/AJ/pkf//fwKAAAAAAAAAAAD6fwIAgQAAAAAAAAD7/wIAFAAAAAAAAADb1NdOR+nTEb/lABCDASLw9JvpI/z/AgBJAAAAAAAAABCguH5m2FcMwOriA8AYiTdAAAAAAAAAAAAgyR4AYyQTwLQHzAz7SjZAAAAAAAAAAABduEBaStByQKo6DX9o7HJAAwAAAFRVlVv/fwKAAAAAAAAAAAD6fwIADgEAAAAAAAD7/wIAFAAAAAAAAAAZEa9eUQvUEb/+ABCDASLwShp5F/z/AgDWAAAAAAAAABEDAAAAAQAAAAMAAAADAAAAAAAAAAAAAAAAAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAAAADwvwAAAAAAAAAAAAAAAAAAAAAEAAAAqjoNf2jsckCqOg1/aOxyQMBct3z5+HJAwFy3fPn4ckADAAAAIMkeAGMkE8C0B8wM+0o2QAAAAAAAAAAAAAAAAAAA8D/MyvaadcQSwOTCch5KUzRAAAAAAAAAAAC0jTLPa5DtP5Cw7sx2+BXAlAEAAAAANkAAAAAAAAAAAAAAAAAAAPA/AJrmXOH/fwKAAAAAAAAAAAD6fwIAgQAAAAAAAAD7/wIAFAAAAAAAAADb1NdOR+nTEb/lABCDASLw9JvpI/z/AgBJAAAAAAAAABCQsO7MdvgVwJQBAAAAADZAAAAAAAAAAADAQw8AAAAXwJQBAAAAADZAAAAAAAAAAADAXLd8+fhyQA3fg6EX/XJAAwAAAGrl77H/fwKAAAAAAAAAAAD6fwIADgEAAAAAAAD7/wIAFAAAAAAAAAAZEa9eUQvUEb/+ABCDASLwShp5F/z/AgDWAAAAAAAAABEDAAAAAQAAAAMAAAADAAAAAAAAAAAAAAAAAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAAAADwvwAAAAAAAAAAAAAAAAAAAAAEAAAADd+DoRf9ckAN34OhF/1yQDkj2Jw5FnNAOSPYnDkWc0ADAAAAwEMPAAAAF8CSAQAAAAA2QAAAAAAAAAAAAAAAAAAA8D9pMR7Ae60RwIDz7szZHC9AAAAAAAAAAAAYO39mnqDmP8BDDwAAABnAkgEAAACANUAAAAAAAAAAAAAAAAAAAPA/AP5ZqOn/fwKAAAAAAAAAAAD6fwIAgQAAAAAAAAD7/wIAFAAAAAAAAADb1NdOR+nTEb/lABCDASLw9JvpI/z/AgBJAAAAAAAAABDAQw8AAAAZwJIBAAAAgDVAAAAAAAAAAADAQw8AAAAZwJIBAAAAgDRAAAAAAAAAAAA5I9icORZzQDoj2Jw5JnNAAwAAAFXY3Qb/fwKAAAAAAAAAAAD6fwIADgEAAAAAAAD7/wIAFAAAAAAAAAAZEa9eUQvUEb/+ABCDASLwShp5F/z/AgDWAAAAAAAAABEDAAAAAQAAAAMAAAADAAAAAAAAAAAAAAAAAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAAAADwvwAAAAAAAAAAAAAAAAAAAAAEAAAAOiPYnDkmc0A6I9icOSZzQGdnLJhbP3NAZ2csmFs/c0ADAAAAwEMPAAAAGcCSAQAAAIA0QAAAAAAAAAAAAAAAAAAA8D9sMh7Ae60RwOANHwDGSCxAAAAAAAAAAACCPH9mnqDmP8BDDwAAABfAkgEAAAAANEAAAAAAAAAAAAAAAAAAAPA/ALAiVMX/fwKAAAAAAAAAAADMj1XL/38CgAAAAAAAAAAA"}))


def trimnextend(crv, t):
    crvn = crv.Trim(t, 1.0)
    # print(crv)
    return crvn


def ln(ca, cb, ta, tb):
    c = rgg.Line(ca.PointAt(ta), cb.PointAt(tb))
    return c


def cpln(ln):
    c = rgg.Line(ln.From, ln.To)
    return c


def extend(c, prm):
    c2 = cpln(c)
    c2.Extend(prm, prm)

    return c2


def pln(cc3):
    cc = cc3.ToNurbsCurve()
    _, e = cc.FrameAt(0)
    e.Rotate(pi / 2, e.YAxis)
    return e


# vva=rgg.Vector3d(points-tl)
# vva.Unitize()
# vval=vva*600


def cyl(line, prm):
    lne = extend(line, 10000)
    return rgg.Cylinder(rgg.Circle(pln(lne), prm), lne.Length)


def cl(ca, cb, prm, ta, tb):
    a = ca.Trim(ta, ca.Domain.T1)
    b = cb.Trim(tb, cb.Domain.T1)
    cylinder = cyl(ln(a, b, ta, tb), prm)
    newcrva = rgg.Intersect.Intersection.CurveSurface(a, cylinder.ToNurbsSurface(), 0.01, 0.01)[0].ParameterA
    newcrvb = rgg.Intersect.Intersection.CurveSurface(b, cylinder.ToNurbsSurface(), 0.01, 0.01)[0].ParameterA
    return a, b, newcrva, newcrvb


def plns(ca, cb, t1a, t1b, t2a, t2b):
    z11 = rgg.Vector3d(cb.PointAt(t1b) - ca.PointAt(t1a))
    ll = extend(ln(ca, cb, t2a, t2b), 10000)
    x2 = rgg.Vector3d(cb.PointAt(t1b) - ll.ClosestPoint(cb.PointAt(t1b), True))

    x1 = rgg.Vector3d(ca.PointAt(t1a) - ll.ClosestPoint(ca.PointAt(t1a), True))

    pln1 = rgg.Plane(ca.PointAt(t1a), x1, rgg.Vector3d.CrossProduct(x1, z11))
    pln2 = rgg.Plane(cb.PointAt(t1b), x2, rgg.Vector3d.CrossProduct(x2, z11))

    return pln1, pln2


def create_buffer(indices, verts, normals, uv):
    return {
        "uuid": uuid.uuid4().__str__(),
        "type": "BufferGeometry",
        "data": {
            "attributes": {
                "normal": {
                    "array": np.asarray(normals, dtype=float).flatten().tolist(),
                    "itemSize": 3,
                    "type": "Float32Array",
                    "normalized": False
                },
                "position": {
                    "array": np.asarray(verts, dtype=float).flatten().tolist(),
                    "itemSize": 3,
                    "type": "Float32Array",
                    "normalized": False
                },
                "uv": {
                    'itemSize': 2,
                    "array": np.asarray(uv, dtype=float).flatten().tolist(),
                    "type": "Float32Array",
                    "normalized": False

                },

            },
            "index": dict(type='Uint16Array',
                          array=np.asarray(indices, dtype=int).flatten().tolist())
        }
    }


Tuple2dVec = TupleUV = Tuple2dPt = EpsTuple[float, float]
Tuple3dPt = Tuple3dVec = EpsTuple[float, float, float]
Tuple4dPt = TupleWPt = EpsTuple[float, float, float, float]


def get_mesh_uv(msh): return [(i.X, i.Y) for i in list(msh.TextureCoordinates)]


def get_np_mesh_uv(msh): return np.asarray(get_mesh_uv(msh))


def get_mesh_vertices(msh): return [(i.X, i.Y, i.Z) for i in list(msh.Vertices)]


def get_np_mesh_vertices(msh): return np.asarray(get_mesh_vertices(msh))


def get_mesh_normals(msh): return [(i.X, i.Y, i.Z) for i in list(msh.Normals)]


def get_np_mesh_normals(msh): return np.asarray(get_mesh_normals(msh))


def mesh_decomposition(msh):
    f = msh.Faces
    f.ConvertQuadsToTriangles()
    vertss = get_mesh_vertices(msh)
    normals = get_mesh_normals(msh)
    llst = []
    vv = []
    for i in range(f.TriangleCount):
        pts = f.GetFaceVertices(i)
        lst = []
        for i in range(3):
            pt = pts[i + 1]
            vv.append((pt.X, pt.Y, pt.Z))
            try:
                lst.append(vertss.index((pt.X, pt.Y, pt.Z)))
            except ValueError as err:
                vrt = list(range(len(vertss)))
                vrt.sort(key=lambda x: spdist.cosine([pt.X, pt.Y, pt.Z], vertss[x]))
                lst.append(vrt[0])

        llst.append(lst)

    return llst, vertss, normals


def brep_to_buffer_mesh(brep,

                        name="Extrusion",

                        cast_shadow=True,
                        receive_shadow=True,
                        layers=1,
                        matrix=(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1)):
    geom = brep_to_buf(brep)
    return {
        "geometries": [geom],
        "materials": [],
        "object": {
            "uuid": uuid.uuid4().__str__(),
            "type": "Mesh",
            "name": name,
            "castShadow": cast_shadow,
            "receiveShadow": receive_shadow,
            "layers": layers,
            "matrix": matrix,
            "geometry": geom["uuid"],
            "material": None
        }}


def mesh_to_buf(mesh):
    return create_buffer(*mesh_decomposition(mesh), get_mesh_uv(mesh))


def brep_to_buf(brep):
    return mesh_to_buf(list(rgg.Mesh.CreateFromBrep(brep, rgg.MeshingParameters.FastRenderMesh))[0])


def prof_extrusion(prof, vec, xf):
    ext = rgg.Extrusion.Create(prof, vec.Length, True)
    ext.Transform(xf)

    return ext.ToBrep(False)


def next_body(self):
    self.ca1, self.cb1, self.ta1, self.tb1 = cl(self.ca, self.cb, self.prm, self.ta, self.tb)
    res1 = ln(self.ca1, self.cb1, self.ta1, self.tb1)
    plna, plnb = plns(self.ca1, self.cb1, self.ta, self.tb, self.ta1, self.tb1)
    xf = rgg.Transform.PlaneToPlane(rgg.Plane.WorldXY, plnb)
    vec = rgg.Vector3d(plna.Origin - plnb.Origin)
    extr = prof_extrusion(self.prof, vec, xf)
    self.ta, self.tb, self.ca, self.cb = self.ta1, self.tb1, self.ca1, self.cb1
    return extr, res1


class CellingGenerator:
    def __init__(self, crvs, starts, prm):
        self.ca, self.cb = crvs
        self.ta, self.tb = starts
        self.prm = prm
        self.prof = get_prof()
        self._i = -1
        self.lines = []

    def __iter__(self):
        return self

    def __next__(self):
        self._i += 1

        try:
            # self.ca, self.cb, self.ta, self.tb = cl(self.ca, self.cb, self.prm, self.ta, self.tb)
            # line = ln(self.ca, self.cb, self.ta, self.tb)
            extr, line = next_body(self)
            return {"extrusion": brep_to_buffer_mesh(extr), "line": [
                {
                    "x": line.From.X,
                    "y": line.From.Y,
                    "z": line.From.Z},
                {
                    "x": line.To.X,
                    "y": line.To.Y,
                    "z": line.To.Z
                }
            ]}

        except Exception as err:

            raise StopIteration()

    def __getitem__(self, item):
        l = None
        for i in range(item):
            l = self.next()
        return l


def generate_point(point):
    return rgg.Point3d(point["x"], point["y"], point["z"])


def generate_points(points):
    return [generate_point(point) for point in points]


def generate_polyline(points):
    return rgg.Polyline(generate_points(points)).ToPolylineCurve()


def extend_curve(curve, start=0.0, end=0.0):
    curve = curve.Extend(rgg.CurveEnd.Start, start, rgg.CurveExtensionStyle.Line)
    curve = curve.Extend(rgg.CurveEnd.End, end, rgg.CurveExtensionStyle.Line)
    return curve
